version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "set COMPOSE_CONVERT_WINDOWS_PATHS=1";
      sh -c "python manage.py runserver 0.0.0.0:8000";
